# Generated by Django 4.2.8 on 2024-02-29 15:38

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Employer name')),
                ('about', models.TextField(blank=True, null=True, verbose_name='About employer')),
                ('foundation_date', models.PositiveSmallIntegerField(verbose_name='Date of foundation of the company')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('number', models.CharField(max_length=13, verbose_name='Number')),
                ('company_photo', image_optimizer.fields.OptimizedImageField(upload_to='employer-photos/%Y/%m/%d', verbose_name='Company logo')),
                ('city', models.CharField(max_length=128, verbose_name='Location of the company')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
    ]
